/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbonnementsRouteImport } from './routes/abonnements'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as BeneficesRouteImport } from './routes/benefices'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CentreAideRouteImport } from './routes/centre-aide'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ConditionsUtilisationRouteImport } from './routes/conditions-utilisation'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactezNousRouteImport } from './routes/contactez-nous'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as FacturesRouteImport } from './routes/factures'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as FonctionnementRouteImport } from './routes/fonctionnement'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MisesAJourRouteImport } from './routes/mises-a-jour'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as NouveautesRouteImport } from './routes/nouveautes'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PlanSiteRouteImport } from './routes/plan-site'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TresorerieRouteImport } from './routes/tresorerie'
import { Route as PortailIdRouteImport } from './routes/portail.$id'
import { Route as ApiAiGenerateQuoteRouteImport } from './routes/api/ai/generate-quote'
import { Route as ApiAiOcrExpenseRouteImport } from './routes/api/ai/ocr-expense'
import { Route as ApiCalendarEventsRouteImport } from './routes/api/calendar/events'
import { Route as ApiCalendarListRouteImport } from './routes/api/calendar/list'
import { Route as ApiCronRelancesRouteImport } from './routes/api/cron/relances'
import { Route as ApiDocumentsDocusealWebhookRouteImport } from './routes/api/documents/docuseal-webhook'
import { Route as ApiQuotesDocusealStartRouteImport } from './routes/api/quotes/docuseal-start'
import { Route as ApiQuotesGetRouteImport } from './routes/api/quotes/get'
import { Route as ApiQuotesRefuseRouteImport } from './routes/api/quotes/refuse'
import { Route as ApiQuotesSendRouteImport } from './routes/api/quotes/send'
import { Route as ApiQuotesSignRouteImport } from './routes/api/quotes/sign'
import { Route as ApiStripeCancelRouteImport } from './routes/api/stripe/cancel'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiStripePortalRouteImport } from './routes/api/stripe/portal'
import { Route as ApiStripeStatusRouteImport } from './routes/api/stripe/status'
import { Route as ApiStripeVerifySessionRouteImport } from './routes/api/stripe/verify-session'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiTeamInviteRouteImport } from './routes/api/team/invite'
import { Route as ApiViesCheckRouteImport } from './routes/api/vies/check'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as ApiAuthGoogleConsumeTokenRouteImport } from './routes/api/auth/google/consume-token'
import { Route as ApiAuthGoogleLoginRouteImport } from './routes/api/auth/google/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementsRoute = AbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficesRoute = BeneficesRouteImport.update({
  id: '/benefices',
  path: '/benefices',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreAideRoute = CentreAideRouteImport.update({
  id: '/centre-aide',
  path: '/centre-aide',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsUtilisationRoute = ConditionsUtilisationRouteImport.update({
  id: '/conditions-utilisation',
  path: '/conditions-utilisation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactezNousRoute = ContactezNousRouteImport.update({
  id: '/contactez-nous',
  path: '/contactez-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesRoute = FacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnementRoute = FonctionnementRouteImport.update({
  id: '/fonctionnement',
  path: '/fonctionnement',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MisesAJourRoute = MisesAJourRouteImport.update({
  id: '/mises-a-jour',
  path: '/mises-a-jour',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveautesRoute = NouveautesRouteImport.update({
  id: '/nouveautes',
  path: '/nouveautes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanSiteRoute = PlanSiteRouteImport.update({
  id: '/plan-site',
  path: '/plan-site',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TresorerieRoute = TresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => rootRouteImport,
} as any)
const PortailIdRoute = PortailIdRouteImport.update({
  id: '/portail/$id',
  path: '/portail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateQuoteRoute = ApiAiGenerateQuoteRouteImport.update({
  id: '/api/ai/generate-quote',
  path: '/api/ai/generate-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiOcrExpenseRoute = ApiAiOcrExpenseRouteImport.update({
  id: '/api/ai/ocr-expense',
  path: '/api/ai/ocr-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventsRoute = ApiCalendarEventsRouteImport.update({
  id: '/api/calendar/events',
  path: '/api/calendar/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarListRoute = ApiCalendarListRouteImport.update({
  id: '/api/calendar/list',
  path: '/api/calendar/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRelancesRoute = ApiCronRelancesRouteImport.update({
  id: '/api/cron/relances',
  path: '/api/cron/relances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsDocusealWebhookRoute =
  ApiDocumentsDocusealWebhookRouteImport.update({
    id: '/api/documents/docuseal-webhook',
    path: '/api/documents/docuseal-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuotesDocusealStartRoute = ApiQuotesDocusealStartRouteImport.update({
  id: '/api/quotes/docuseal-start',
  path: '/api/quotes/docuseal-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesGetRoute = ApiQuotesGetRouteImport.update({
  id: '/api/quotes/get',
  path: '/api/quotes/get',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesRefuseRoute = ApiQuotesRefuseRouteImport.update({
  id: '/api/quotes/refuse',
  path: '/api/quotes/refuse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesSendRoute = ApiQuotesSendRouteImport.update({
  id: '/api/quotes/send',
  path: '/api/quotes/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesSignRoute = ApiQuotesSignRouteImport.update({
  id: '/api/quotes/sign',
  path: '/api/quotes/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCancelRoute = ApiStripeCancelRouteImport.update({
  id: '/api/stripe/cancel',
  path: '/api/stripe/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripePortalRoute = ApiStripePortalRouteImport.update({
  id: '/api/stripe/portal',
  path: '/api/stripe/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeStatusRoute = ApiStripeStatusRouteImport.update({
  id: '/api/stripe/status',
  path: '/api/stripe/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeVerifySessionRoute = ApiStripeVerifySessionRouteImport.update({
  id: '/api/stripe/verify-session',
  path: '/api/stripe/verify-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamInviteRoute = ApiTeamInviteRouteImport.update({
  id: '/api/team/invite',
  path: '/api/team/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiViesCheckRoute = ApiViesCheckRouteImport.update({
  id: '/api/vies/check',
  path: '/api/vies/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleConsumeTokenRoute =
  ApiAuthGoogleConsumeTokenRouteImport.update({
    id: '/api/auth/google/consume-token',
    path: '/api/auth/google/consume-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGoogleLoginRoute = ApiAuthGoogleLoginRouteImport.update({
  id: '/api/auth/google/login',
  path: '/api/auth/google/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/archives': typeof ArchivesRoute
  '/benefices': typeof BeneficesRoute
  '/catalogue': typeof CatalogueRoute
  '/centre-aide': typeof CentreAideRoute
  '/clients': typeof ClientsRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contactez-nous': typeof ContactezNousRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/factures': typeof FacturesRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/fonctionnement': typeof FonctionnementRoute
  '/inscription': typeof InscriptionRoute
  '/legal': typeof LegalRoute
  '/mises-a-jour': typeof MisesAJourRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveautes': typeof NouveautesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/plan-site': typeof PlanSiteRoute
  '/rendez-vous': typeof RendezVousRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/tarifs': typeof TarifsRoute
  '/tresorerie': typeof TresorerieRoute
  '/portail/$id': typeof PortailIdRoute
  '/api/ai/generate-quote': typeof ApiAiGenerateQuoteRoute
  '/api/ai/ocr-expense': typeof ApiAiOcrExpenseRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/list': typeof ApiCalendarListRoute
  '/api/cron/relances': typeof ApiCronRelancesRoute
  '/api/documents/docuseal-webhook': typeof ApiDocumentsDocusealWebhookRoute
  '/api/quotes/docuseal-start': typeof ApiQuotesDocusealStartRoute
  '/api/quotes/get': typeof ApiQuotesGetRoute
  '/api/quotes/refuse': typeof ApiQuotesRefuseRoute
  '/api/quotes/send': typeof ApiQuotesSendRoute
  '/api/quotes/sign': typeof ApiQuotesSignRoute
  '/api/stripe/cancel': typeof ApiStripeCancelRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/status': typeof ApiStripeStatusRoute
  '/api/stripe/verify-session': typeof ApiStripeVerifySessionRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/team/invite': typeof ApiTeamInviteRoute
  '/api/vies/check': typeof ApiViesCheckRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/consume-token': typeof ApiAuthGoogleConsumeTokenRoute
  '/api/auth/google/login': typeof ApiAuthGoogleLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/archives': typeof ArchivesRoute
  '/benefices': typeof BeneficesRoute
  '/catalogue': typeof CatalogueRoute
  '/centre-aide': typeof CentreAideRoute
  '/clients': typeof ClientsRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contactez-nous': typeof ContactezNousRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/factures': typeof FacturesRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/fonctionnement': typeof FonctionnementRoute
  '/inscription': typeof InscriptionRoute
  '/legal': typeof LegalRoute
  '/mises-a-jour': typeof MisesAJourRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveautes': typeof NouveautesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/plan-site': typeof PlanSiteRoute
  '/rendez-vous': typeof RendezVousRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/tarifs': typeof TarifsRoute
  '/tresorerie': typeof TresorerieRoute
  '/portail/$id': typeof PortailIdRoute
  '/api/ai/generate-quote': typeof ApiAiGenerateQuoteRoute
  '/api/ai/ocr-expense': typeof ApiAiOcrExpenseRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/list': typeof ApiCalendarListRoute
  '/api/cron/relances': typeof ApiCronRelancesRoute
  '/api/documents/docuseal-webhook': typeof ApiDocumentsDocusealWebhookRoute
  '/api/quotes/docuseal-start': typeof ApiQuotesDocusealStartRoute
  '/api/quotes/get': typeof ApiQuotesGetRoute
  '/api/quotes/refuse': typeof ApiQuotesRefuseRoute
  '/api/quotes/send': typeof ApiQuotesSendRoute
  '/api/quotes/sign': typeof ApiQuotesSignRoute
  '/api/stripe/cancel': typeof ApiStripeCancelRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/status': typeof ApiStripeStatusRoute
  '/api/stripe/verify-session': typeof ApiStripeVerifySessionRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/team/invite': typeof ApiTeamInviteRoute
  '/api/vies/check': typeof ApiViesCheckRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/consume-token': typeof ApiAuthGoogleConsumeTokenRoute
  '/api/auth/google/login': typeof ApiAuthGoogleLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/archives': typeof ArchivesRoute
  '/benefices': typeof BeneficesRoute
  '/catalogue': typeof CatalogueRoute
  '/centre-aide': typeof CentreAideRoute
  '/clients': typeof ClientsRoute
  '/conditions-utilisation': typeof ConditionsUtilisationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contactez-nous': typeof ContactezNousRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/factures': typeof FacturesRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/fonctionnement': typeof FonctionnementRoute
  '/inscription': typeof InscriptionRoute
  '/legal': typeof LegalRoute
  '/mises-a-jour': typeof MisesAJourRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveautes': typeof NouveautesRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/plan-site': typeof PlanSiteRoute
  '/rendez-vous': typeof RendezVousRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/tarifs': typeof TarifsRoute
  '/tresorerie': typeof TresorerieRoute
  '/portail/$id': typeof PortailIdRoute
  '/api/ai/generate-quote': typeof ApiAiGenerateQuoteRoute
  '/api/ai/ocr-expense': typeof ApiAiOcrExpenseRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/calendar/list': typeof ApiCalendarListRoute
  '/api/cron/relances': typeof ApiCronRelancesRoute
  '/api/documents/docuseal-webhook': typeof ApiDocumentsDocusealWebhookRoute
  '/api/quotes/docuseal-start': typeof ApiQuotesDocusealStartRoute
  '/api/quotes/get': typeof ApiQuotesGetRoute
  '/api/quotes/refuse': typeof ApiQuotesRefuseRoute
  '/api/quotes/send': typeof ApiQuotesSendRoute
  '/api/quotes/sign': typeof ApiQuotesSignRoute
  '/api/stripe/cancel': typeof ApiStripeCancelRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/stripe/portal': typeof ApiStripePortalRoute
  '/api/stripe/status': typeof ApiStripeStatusRoute
  '/api/stripe/verify-session': typeof ApiStripeVerifySessionRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/team/invite': typeof ApiTeamInviteRoute
  '/api/vies/check': typeof ApiViesCheckRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/consume-token': typeof ApiAuthGoogleConsumeTokenRoute
  '/api/auth/google/login': typeof ApiAuthGoogleLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnements'
    | '/archives'
    | '/benefices'
    | '/catalogue'
    | '/centre-aide'
    | '/clients'
    | '/conditions-utilisation'
    | '/confidentialite'
    | '/connexion'
    | '/contactez-nous'
    | '/depenses'
    | '/devis'
    | '/factures'
    | '/fonctionnalites'
    | '/fonctionnement'
    | '/inscription'
    | '/legal'
    | '/mises-a-jour'
    | '/mot-de-passe-oublie'
    | '/nouveautes'
    | '/paiements'
    | '/parametres'
    | '/pipeline'
    | '/plan-site'
    | '/rendez-vous'
    | '/tableau-de-bord'
    | '/tarifs'
    | '/tresorerie'
    | '/portail/$id'
    | '/api/ai/generate-quote'
    | '/api/ai/ocr-expense'
    | '/api/calendar/events'
    | '/api/calendar/list'
    | '/api/cron/relances'
    | '/api/documents/docuseal-webhook'
    | '/api/quotes/docuseal-start'
    | '/api/quotes/get'
    | '/api/quotes/refuse'
    | '/api/quotes/send'
    | '/api/quotes/sign'
    | '/api/stripe/cancel'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/status'
    | '/api/stripe/verify-session'
    | '/api/stripe/webhook'
    | '/api/team/invite'
    | '/api/vies/check'
    | '/api/auth/google/callback'
    | '/api/auth/google/consume-token'
    | '/api/auth/google/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnements'
    | '/archives'
    | '/benefices'
    | '/catalogue'
    | '/centre-aide'
    | '/clients'
    | '/conditions-utilisation'
    | '/confidentialite'
    | '/connexion'
    | '/contactez-nous'
    | '/depenses'
    | '/devis'
    | '/factures'
    | '/fonctionnalites'
    | '/fonctionnement'
    | '/inscription'
    | '/legal'
    | '/mises-a-jour'
    | '/mot-de-passe-oublie'
    | '/nouveautes'
    | '/paiements'
    | '/parametres'
    | '/pipeline'
    | '/plan-site'
    | '/rendez-vous'
    | '/tableau-de-bord'
    | '/tarifs'
    | '/tresorerie'
    | '/portail/$id'
    | '/api/ai/generate-quote'
    | '/api/ai/ocr-expense'
    | '/api/calendar/events'
    | '/api/calendar/list'
    | '/api/cron/relances'
    | '/api/documents/docuseal-webhook'
    | '/api/quotes/docuseal-start'
    | '/api/quotes/get'
    | '/api/quotes/refuse'
    | '/api/quotes/send'
    | '/api/quotes/sign'
    | '/api/stripe/cancel'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/status'
    | '/api/stripe/verify-session'
    | '/api/stripe/webhook'
    | '/api/team/invite'
    | '/api/vies/check'
    | '/api/auth/google/callback'
    | '/api/auth/google/consume-token'
    | '/api/auth/google/login'
  id:
    | '__root__'
    | '/'
    | '/abonnements'
    | '/archives'
    | '/benefices'
    | '/catalogue'
    | '/centre-aide'
    | '/clients'
    | '/conditions-utilisation'
    | '/confidentialite'
    | '/connexion'
    | '/contactez-nous'
    | '/depenses'
    | '/devis'
    | '/factures'
    | '/fonctionnalites'
    | '/fonctionnement'
    | '/inscription'
    | '/legal'
    | '/mises-a-jour'
    | '/mot-de-passe-oublie'
    | '/nouveautes'
    | '/paiements'
    | '/parametres'
    | '/pipeline'
    | '/plan-site'
    | '/rendez-vous'
    | '/tableau-de-bord'
    | '/tarifs'
    | '/tresorerie'
    | '/portail/$id'
    | '/api/ai/generate-quote'
    | '/api/ai/ocr-expense'
    | '/api/calendar/events'
    | '/api/calendar/list'
    | '/api/cron/relances'
    | '/api/documents/docuseal-webhook'
    | '/api/quotes/docuseal-start'
    | '/api/quotes/get'
    | '/api/quotes/refuse'
    | '/api/quotes/send'
    | '/api/quotes/sign'
    | '/api/stripe/cancel'
    | '/api/stripe/checkout'
    | '/api/stripe/portal'
    | '/api/stripe/status'
    | '/api/stripe/verify-session'
    | '/api/stripe/webhook'
    | '/api/team/invite'
    | '/api/vies/check'
    | '/api/auth/google/callback'
    | '/api/auth/google/consume-token'
    | '/api/auth/google/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementsRoute: typeof AbonnementsRoute
  ArchivesRoute: typeof ArchivesRoute
  BeneficesRoute: typeof BeneficesRoute
  CatalogueRoute: typeof CatalogueRoute
  CentreAideRoute: typeof CentreAideRoute
  ClientsRoute: typeof ClientsRoute
  ConditionsUtilisationRoute: typeof ConditionsUtilisationRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactezNousRoute: typeof ContactezNousRoute
  DepensesRoute: typeof DepensesRoute
  DevisRoute: typeof DevisRoute
  FacturesRoute: typeof FacturesRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  FonctionnementRoute: typeof FonctionnementRoute
  InscriptionRoute: typeof InscriptionRoute
  LegalRoute: typeof LegalRoute
  MisesAJourRoute: typeof MisesAJourRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NouveautesRoute: typeof NouveautesRoute
  PaiementsRoute: typeof PaiementsRoute
  ParametresRoute: typeof ParametresRoute
  PipelineRoute: typeof PipelineRoute
  PlanSiteRoute: typeof PlanSiteRoute
  RendezVousRoute: typeof RendezVousRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
  TarifsRoute: typeof TarifsRoute
  TresorerieRoute: typeof TresorerieRoute
  PortailIdRoute: typeof PortailIdRoute
  ApiAiGenerateQuoteRoute: typeof ApiAiGenerateQuoteRoute
  ApiAiOcrExpenseRoute: typeof ApiAiOcrExpenseRoute
  ApiCalendarEventsRoute: typeof ApiCalendarEventsRoute
  ApiCalendarListRoute: typeof ApiCalendarListRoute
  ApiCronRelancesRoute: typeof ApiCronRelancesRoute
  ApiDocumentsDocusealWebhookRoute: typeof ApiDocumentsDocusealWebhookRoute
  ApiQuotesDocusealStartRoute: typeof ApiQuotesDocusealStartRoute
  ApiQuotesGetRoute: typeof ApiQuotesGetRoute
  ApiQuotesRefuseRoute: typeof ApiQuotesRefuseRoute
  ApiQuotesSendRoute: typeof ApiQuotesSendRoute
  ApiQuotesSignRoute: typeof ApiQuotesSignRoute
  ApiStripeCancelRoute: typeof ApiStripeCancelRoute
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiStripePortalRoute: typeof ApiStripePortalRoute
  ApiStripeStatusRoute: typeof ApiStripeStatusRoute
  ApiStripeVerifySessionRoute: typeof ApiStripeVerifySessionRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiTeamInviteRoute: typeof ApiTeamInviteRoute
  ApiViesCheckRoute: typeof ApiViesCheckRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleConsumeTokenRoute: typeof ApiAuthGoogleConsumeTokenRoute
  ApiAuthGoogleLoginRoute: typeof ApiAuthGoogleLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnements': {
      id: '/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefices': {
      id: '/benefices'
      path: '/benefices'
      fullPath: '/benefices'
      preLoaderRoute: typeof BeneficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre-aide': {
      id: '/centre-aide'
      path: '/centre-aide'
      fullPath: '/centre-aide'
      preLoaderRoute: typeof CentreAideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-utilisation': {
      id: '/conditions-utilisation'
      path: '/conditions-utilisation'
      fullPath: '/conditions-utilisation'
      preLoaderRoute: typeof ConditionsUtilisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactez-nous': {
      id: '/contactez-nous'
      path: '/contactez-nous'
      fullPath: '/contactez-nous'
      preLoaderRoute: typeof ContactezNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures': {
      id: '/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof FacturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnement': {
      id: '/fonctionnement'
      path: '/fonctionnement'
      fullPath: '/fonctionnement'
      preLoaderRoute: typeof FonctionnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mises-a-jour': {
      id: '/mises-a-jour'
      path: '/mises-a-jour'
      fullPath: '/mises-a-jour'
      preLoaderRoute: typeof MisesAJourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveautes': {
      id: '/nouveautes'
      path: '/nouveautes'
      fullPath: '/nouveautes'
      preLoaderRoute: typeof NouveautesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-site': {
      id: '/plan-site'
      path: '/plan-site'
      fullPath: '/plan-site'
      preLoaderRoute: typeof PlanSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tresorerie': {
      id: '/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof TresorerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portail/$id': {
      id: '/portail/$id'
      path: '/portail/$id'
      fullPath: '/portail/$id'
      preLoaderRoute: typeof PortailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-quote': {
      id: '/api/ai/generate-quote'
      path: '/api/ai/generate-quote'
      fullPath: '/api/ai/generate-quote'
      preLoaderRoute: typeof ApiAiGenerateQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/ocr-expense': {
      id: '/api/ai/ocr-expense'
      path: '/api/ai/ocr-expense'
      fullPath: '/api/ai/ocr-expense'
      preLoaderRoute: typeof ApiAiOcrExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/events': {
      id: '/api/calendar/events'
      path: '/api/calendar/events'
      fullPath: '/api/calendar/events'
      preLoaderRoute: typeof ApiCalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/list': {
      id: '/api/calendar/list'
      path: '/api/calendar/list'
      fullPath: '/api/calendar/list'
      preLoaderRoute: typeof ApiCalendarListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/relances': {
      id: '/api/cron/relances'
      path: '/api/cron/relances'
      fullPath: '/api/cron/relances'
      preLoaderRoute: typeof ApiCronRelancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/docuseal-webhook': {
      id: '/api/documents/docuseal-webhook'
      path: '/api/documents/docuseal-webhook'
      fullPath: '/api/documents/docuseal-webhook'
      preLoaderRoute: typeof ApiDocumentsDocusealWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/docuseal-start': {
      id: '/api/quotes/docuseal-start'
      path: '/api/quotes/docuseal-start'
      fullPath: '/api/quotes/docuseal-start'
      preLoaderRoute: typeof ApiQuotesDocusealStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/get': {
      id: '/api/quotes/get'
      path: '/api/quotes/get'
      fullPath: '/api/quotes/get'
      preLoaderRoute: typeof ApiQuotesGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/refuse': {
      id: '/api/quotes/refuse'
      path: '/api/quotes/refuse'
      fullPath: '/api/quotes/refuse'
      preLoaderRoute: typeof ApiQuotesRefuseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/send': {
      id: '/api/quotes/send'
      path: '/api/quotes/send'
      fullPath: '/api/quotes/send'
      preLoaderRoute: typeof ApiQuotesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes/sign': {
      id: '/api/quotes/sign'
      path: '/api/quotes/sign'
      fullPath: '/api/quotes/sign'
      preLoaderRoute: typeof ApiQuotesSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/cancel': {
      id: '/api/stripe/cancel'
      path: '/api/stripe/cancel'
      fullPath: '/api/stripe/cancel'
      preLoaderRoute: typeof ApiStripeCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/portal': {
      id: '/api/stripe/portal'
      path: '/api/stripe/portal'
      fullPath: '/api/stripe/portal'
      preLoaderRoute: typeof ApiStripePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/status': {
      id: '/api/stripe/status'
      path: '/api/stripe/status'
      fullPath: '/api/stripe/status'
      preLoaderRoute: typeof ApiStripeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/verify-session': {
      id: '/api/stripe/verify-session'
      path: '/api/stripe/verify-session'
      fullPath: '/api/stripe/verify-session'
      preLoaderRoute: typeof ApiStripeVerifySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/invite': {
      id: '/api/team/invite'
      path: '/api/team/invite'
      fullPath: '/api/team/invite'
      preLoaderRoute: typeof ApiTeamInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vies/check': {
      id: '/api/vies/check'
      path: '/api/vies/check'
      fullPath: '/api/vies/check'
      preLoaderRoute: typeof ApiViesCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/consume-token': {
      id: '/api/auth/google/consume-token'
      path: '/api/auth/google/consume-token'
      fullPath: '/api/auth/google/consume-token'
      preLoaderRoute: typeof ApiAuthGoogleConsumeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/login': {
      id: '/api/auth/google/login'
      path: '/api/auth/google/login'
      fullPath: '/api/auth/google/login'
      preLoaderRoute: typeof ApiAuthGoogleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementsRoute: AbonnementsRoute,
  ArchivesRoute: ArchivesRoute,
  BeneficesRoute: BeneficesRoute,
  CatalogueRoute: CatalogueRoute,
  CentreAideRoute: CentreAideRoute,
  ClientsRoute: ClientsRoute,
  ConditionsUtilisationRoute: ConditionsUtilisationRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactezNousRoute: ContactezNousRoute,
  DepensesRoute: DepensesRoute,
  DevisRoute: DevisRoute,
  FacturesRoute: FacturesRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  FonctionnementRoute: FonctionnementRoute,
  InscriptionRoute: InscriptionRoute,
  LegalRoute: LegalRoute,
  MisesAJourRoute: MisesAJourRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NouveautesRoute: NouveautesRoute,
  PaiementsRoute: PaiementsRoute,
  ParametresRoute: ParametresRoute,
  PipelineRoute: PipelineRoute,
  PlanSiteRoute: PlanSiteRoute,
  RendezVousRoute: RendezVousRoute,
  TableauDeBordRoute: TableauDeBordRoute,
  TarifsRoute: TarifsRoute,
  TresorerieRoute: TresorerieRoute,
  PortailIdRoute: PortailIdRoute,
  ApiAiGenerateQuoteRoute: ApiAiGenerateQuoteRoute,
  ApiAiOcrExpenseRoute: ApiAiOcrExpenseRoute,
  ApiCalendarEventsRoute: ApiCalendarEventsRoute,
  ApiCalendarListRoute: ApiCalendarListRoute,
  ApiCronRelancesRoute: ApiCronRelancesRoute,
  ApiDocumentsDocusealWebhookRoute: ApiDocumentsDocusealWebhookRoute,
  ApiQuotesDocusealStartRoute: ApiQuotesDocusealStartRoute,
  ApiQuotesGetRoute: ApiQuotesGetRoute,
  ApiQuotesRefuseRoute: ApiQuotesRefuseRoute,
  ApiQuotesSendRoute: ApiQuotesSendRoute,
  ApiQuotesSignRoute: ApiQuotesSignRoute,
  ApiStripeCancelRoute: ApiStripeCancelRoute,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiStripePortalRoute: ApiStripePortalRoute,
  ApiStripeStatusRoute: ApiStripeStatusRoute,
  ApiStripeVerifySessionRoute: ApiStripeVerifySessionRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiTeamInviteRoute: ApiTeamInviteRoute,
  ApiViesCheckRoute: ApiViesCheckRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleConsumeTokenRoute: ApiAuthGoogleConsumeTokenRoute,
  ApiAuthGoogleLoginRoute: ApiAuthGoogleLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
