/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AidesFinancieres2026RouteImport } from './routes/aides-financieres-2026'
import { Route as AuditEnergetiqueRouteImport } from './routes/audit-energetique'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EcoPtzRouteImport } from './routes/eco-ptz'
import { Route as IsolationComblesRouteImport } from './routes/isolation-combles'
import { Route as IsolationMursRouteImport } from './routes/isolation-murs'
import { Route as IsolationPlanchersRouteImport } from './routes/isolation-planchers'
import { Route as IsolationThermiqueRouteImport } from './routes/isolation-thermique'
import { Route as MaprimerenovRouteImport } from './routes/maprimerenov'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MenuiseriesFenetresRouteImport } from './routes/menuiseries-fenetres'
import { Route as NosZonesDInterventionRouteImport } from './routes/nos-zones-d-intervention'
import { Route as NotreMethodeRouteImport } from './routes/notre-methode'
import { Route as PacAirAirRouteImport } from './routes/pac-air-air'
import { Route as PacAirEauRouteImport } from './routes/pac-air-eau'
import { Route as PacGeothermieRouteImport } from './routes/pac-geothermie'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as PompeAChaleurRouteImport } from './routes/pompe-a-chaleur'
import { Route as PompeAChaleurVsChaudiereGazRouteImport } from './routes/pompe-a-chaleur-vs-chaudiere-gaz'
import { Route as PrimeCeeRouteImport } from './routes/prime-cee'
import { Route as ReequilibrageChauffageRouteImport } from './routes/reequilibrage-chauffage'
import { Route as RenovationAmpleurRouteImport } from './routes/renovation-ampleur'
import { Route as RenovationAppartementRouteImport } from './routes/renovation-appartement'
import { Route as RenovationImmeubleRouteImport } from './routes/renovation-immeuble'
import { Route as RenovationMaisonIndividuelleRouteImport } from './routes/renovation-maison-individuelle'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as VmcVentilationRouteImport } from './routes/vmc-ventilation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AidesFinancieres2026Route = AidesFinancieres2026RouteImport.update({
  id: '/aides-financieres-2026',
  path: '/aides-financieres-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditEnergetiqueRoute = AuditEnergetiqueRouteImport.update({
  id: '/audit-energetique',
  path: '/audit-energetique',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoPtzRoute = EcoPtzRouteImport.update({
  id: '/eco-ptz',
  path: '/eco-ptz',
  getParentRoute: () => rootRouteImport,
} as any)
const IsolationComblesRoute = IsolationComblesRouteImport.update({
  id: '/isolation-combles',
  path: '/isolation-combles',
  getParentRoute: () => rootRouteImport,
} as any)
const IsolationMursRoute = IsolationMursRouteImport.update({
  id: '/isolation-murs',
  path: '/isolation-murs',
  getParentRoute: () => rootRouteImport,
} as any)
const IsolationPlanchersRoute = IsolationPlanchersRouteImport.update({
  id: '/isolation-planchers',
  path: '/isolation-planchers',
  getParentRoute: () => rootRouteImport,
} as any)
const IsolationThermiqueRoute = IsolationThermiqueRouteImport.update({
  id: '/isolation-thermique',
  path: '/isolation-thermique',
  getParentRoute: () => rootRouteImport,
} as any)
const MaprimerenovRoute = MaprimerenovRouteImport.update({
  id: '/maprimerenov',
  path: '/maprimerenov',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuiseriesFenetresRoute = MenuiseriesFenetresRouteImport.update({
  id: '/menuiseries-fenetres',
  path: '/menuiseries-fenetres',
  getParentRoute: () => rootRouteImport,
} as any)
const NosZonesDInterventionRoute = NosZonesDInterventionRouteImport.update({
  id: '/nos-zones-d-intervention',
  path: '/nos-zones-d-intervention',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreMethodeRoute = NotreMethodeRouteImport.update({
  id: '/notre-methode',
  path: '/notre-methode',
  getParentRoute: () => rootRouteImport,
} as any)
const PacAirAirRoute = PacAirAirRouteImport.update({
  id: '/pac-air-air',
  path: '/pac-air-air',
  getParentRoute: () => rootRouteImport,
} as any)
const PacAirEauRoute = PacAirEauRouteImport.update({
  id: '/pac-air-eau',
  path: '/pac-air-eau',
  getParentRoute: () => rootRouteImport,
} as any)
const PacGeothermieRoute = PacGeothermieRouteImport.update({
  id: '/pac-geothermie',
  path: '/pac-geothermie',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PompeAChaleurRoute = PompeAChaleurRouteImport.update({
  id: '/pompe-a-chaleur',
  path: '/pompe-a-chaleur',
  getParentRoute: () => rootRouteImport,
} as any)
const PompeAChaleurVsChaudiereGazRoute =
  PompeAChaleurVsChaudiereGazRouteImport.update({
    id: '/pompe-a-chaleur-vs-chaudiere-gaz',
    path: '/pompe-a-chaleur-vs-chaudiere-gaz',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrimeCeeRoute = PrimeCeeRouteImport.update({
  id: '/prime-cee',
  path: '/prime-cee',
  getParentRoute: () => rootRouteImport,
} as any)
const ReequilibrageChauffageRoute = ReequilibrageChauffageRouteImport.update({
  id: '/reequilibrage-chauffage',
  path: '/reequilibrage-chauffage',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovationAmpleurRoute = RenovationAmpleurRouteImport.update({
  id: '/renovation-ampleur',
  path: '/renovation-ampleur',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovationAppartementRoute = RenovationAppartementRouteImport.update({
  id: '/renovation-appartement',
  path: '/renovation-appartement',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovationImmeubleRoute = RenovationImmeubleRouteImport.update({
  id: '/renovation-immeuble',
  path: '/renovation-immeuble',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovationMaisonIndividuelleRoute =
  RenovationMaisonIndividuelleRouteImport.update({
    id: '/renovation-maison-individuelle',
    path: '/renovation-maison-individuelle',
    getParentRoute: () => rootRouteImport,
  } as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const VmcVentilationRoute = VmcVentilationRouteImport.update({
  id: '/vmc-ventilation',
  path: '/vmc-ventilation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aides-financieres-2026': typeof AidesFinancieres2026Route
  '/audit-energetique': typeof AuditEnergetiqueRoute
  '/contact': typeof ContactRoute
  '/eco-ptz': typeof EcoPtzRoute
  '/isolation-combles': typeof IsolationComblesRoute
  '/isolation-murs': typeof IsolationMursRoute
  '/isolation-planchers': typeof IsolationPlanchersRoute
  '/isolation-thermique': typeof IsolationThermiqueRoute
  '/maprimerenov': typeof MaprimerenovRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/menuiseries-fenetres': typeof MenuiseriesFenetresRoute
  '/nos-zones-d-intervention': typeof NosZonesDInterventionRoute
  '/notre-methode': typeof NotreMethodeRoute
  '/pac-air-air': typeof PacAirAirRoute
  '/pac-air-eau': typeof PacAirEauRoute
  '/pac-geothermie': typeof PacGeothermieRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/pompe-a-chaleur': typeof PompeAChaleurRoute
  '/pompe-a-chaleur-vs-chaudiere-gaz': typeof PompeAChaleurVsChaudiereGazRoute
  '/prime-cee': typeof PrimeCeeRoute
  '/reequilibrage-chauffage': typeof ReequilibrageChauffageRoute
  '/renovation-ampleur': typeof RenovationAmpleurRoute
  '/renovation-appartement': typeof RenovationAppartementRoute
  '/renovation-immeuble': typeof RenovationImmeubleRoute
  '/renovation-maison-individuelle': typeof RenovationMaisonIndividuelleRoute
  '/simulation': typeof SimulationRoute
  '/vmc-ventilation': typeof VmcVentilationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aides-financieres-2026': typeof AidesFinancieres2026Route
  '/audit-energetique': typeof AuditEnergetiqueRoute
  '/contact': typeof ContactRoute
  '/eco-ptz': typeof EcoPtzRoute
  '/isolation-combles': typeof IsolationComblesRoute
  '/isolation-murs': typeof IsolationMursRoute
  '/isolation-planchers': typeof IsolationPlanchersRoute
  '/isolation-thermique': typeof IsolationThermiqueRoute
  '/maprimerenov': typeof MaprimerenovRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/menuiseries-fenetres': typeof MenuiseriesFenetresRoute
  '/nos-zones-d-intervention': typeof NosZonesDInterventionRoute
  '/notre-methode': typeof NotreMethodeRoute
  '/pac-air-air': typeof PacAirAirRoute
  '/pac-air-eau': typeof PacAirEauRoute
  '/pac-geothermie': typeof PacGeothermieRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/pompe-a-chaleur': typeof PompeAChaleurRoute
  '/pompe-a-chaleur-vs-chaudiere-gaz': typeof PompeAChaleurVsChaudiereGazRoute
  '/prime-cee': typeof PrimeCeeRoute
  '/reequilibrage-chauffage': typeof ReequilibrageChauffageRoute
  '/renovation-ampleur': typeof RenovationAmpleurRoute
  '/renovation-appartement': typeof RenovationAppartementRoute
  '/renovation-immeuble': typeof RenovationImmeubleRoute
  '/renovation-maison-individuelle': typeof RenovationMaisonIndividuelleRoute
  '/simulation': typeof SimulationRoute
  '/vmc-ventilation': typeof VmcVentilationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aides-financieres-2026': typeof AidesFinancieres2026Route
  '/audit-energetique': typeof AuditEnergetiqueRoute
  '/contact': typeof ContactRoute
  '/eco-ptz': typeof EcoPtzRoute
  '/isolation-combles': typeof IsolationComblesRoute
  '/isolation-murs': typeof IsolationMursRoute
  '/isolation-planchers': typeof IsolationPlanchersRoute
  '/isolation-thermique': typeof IsolationThermiqueRoute
  '/maprimerenov': typeof MaprimerenovRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/menuiseries-fenetres': typeof MenuiseriesFenetresRoute
  '/nos-zones-d-intervention': typeof NosZonesDInterventionRoute
  '/notre-methode': typeof NotreMethodeRoute
  '/pac-air-air': typeof PacAirAirRoute
  '/pac-air-eau': typeof PacAirEauRoute
  '/pac-geothermie': typeof PacGeothermieRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/pompe-a-chaleur': typeof PompeAChaleurRoute
  '/pompe-a-chaleur-vs-chaudiere-gaz': typeof PompeAChaleurVsChaudiereGazRoute
  '/prime-cee': typeof PrimeCeeRoute
  '/reequilibrage-chauffage': typeof ReequilibrageChauffageRoute
  '/renovation-ampleur': typeof RenovationAmpleurRoute
  '/renovation-appartement': typeof RenovationAppartementRoute
  '/renovation-immeuble': typeof RenovationImmeubleRoute
  '/renovation-maison-individuelle': typeof RenovationMaisonIndividuelleRoute
  '/simulation': typeof SimulationRoute
  '/vmc-ventilation': typeof VmcVentilationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aides-financieres-2026'
    | '/audit-energetique'
    | '/contact'
    | '/eco-ptz'
    | '/isolation-combles'
    | '/isolation-murs'
    | '/isolation-planchers'
    | '/isolation-thermique'
    | '/maprimerenov'
    | '/mentions-legales'
    | '/menuiseries-fenetres'
    | '/nos-zones-d-intervention'
    | '/notre-methode'
    | '/pac-air-air'
    | '/pac-air-eau'
    | '/pac-geothermie'
    | '/politique-de-confidentialite'
    | '/pompe-a-chaleur'
    | '/pompe-a-chaleur-vs-chaudiere-gaz'
    | '/prime-cee'
    | '/reequilibrage-chauffage'
    | '/renovation-ampleur'
    | '/renovation-appartement'
    | '/renovation-immeuble'
    | '/renovation-maison-individuelle'
    | '/simulation'
    | '/vmc-ventilation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aides-financieres-2026'
    | '/audit-energetique'
    | '/contact'
    | '/eco-ptz'
    | '/isolation-combles'
    | '/isolation-murs'
    | '/isolation-planchers'
    | '/isolation-thermique'
    | '/maprimerenov'
    | '/mentions-legales'
    | '/menuiseries-fenetres'
    | '/nos-zones-d-intervention'
    | '/notre-methode'
    | '/pac-air-air'
    | '/pac-air-eau'
    | '/pac-geothermie'
    | '/politique-de-confidentialite'
    | '/pompe-a-chaleur'
    | '/pompe-a-chaleur-vs-chaudiere-gaz'
    | '/prime-cee'
    | '/reequilibrage-chauffage'
    | '/renovation-ampleur'
    | '/renovation-appartement'
    | '/renovation-immeuble'
    | '/renovation-maison-individuelle'
    | '/simulation'
    | '/vmc-ventilation'
  id:
    | '__root__'
    | '/'
    | '/aides-financieres-2026'
    | '/audit-energetique'
    | '/contact'
    | '/eco-ptz'
    | '/isolation-combles'
    | '/isolation-murs'
    | '/isolation-planchers'
    | '/isolation-thermique'
    | '/maprimerenov'
    | '/mentions-legales'
    | '/menuiseries-fenetres'
    | '/nos-zones-d-intervention'
    | '/notre-methode'
    | '/pac-air-air'
    | '/pac-air-eau'
    | '/pac-geothermie'
    | '/politique-de-confidentialite'
    | '/pompe-a-chaleur'
    | '/pompe-a-chaleur-vs-chaudiere-gaz'
    | '/prime-cee'
    | '/reequilibrage-chauffage'
    | '/renovation-ampleur'
    | '/renovation-appartement'
    | '/renovation-immeuble'
    | '/renovation-maison-individuelle'
    | '/simulation'
    | '/vmc-ventilation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AidesFinancieres2026Route: typeof AidesFinancieres2026Route
  AuditEnergetiqueRoute: typeof AuditEnergetiqueRoute
  ContactRoute: typeof ContactRoute
  EcoPtzRoute: typeof EcoPtzRoute
  IsolationComblesRoute: typeof IsolationComblesRoute
  IsolationMursRoute: typeof IsolationMursRoute
  IsolationPlanchersRoute: typeof IsolationPlanchersRoute
  IsolationThermiqueRoute: typeof IsolationThermiqueRoute
  MaprimerenovRoute: typeof MaprimerenovRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MenuiseriesFenetresRoute: typeof MenuiseriesFenetresRoute
  NosZonesDInterventionRoute: typeof NosZonesDInterventionRoute
  NotreMethodeRoute: typeof NotreMethodeRoute
  PacAirAirRoute: typeof PacAirAirRoute
  PacAirEauRoute: typeof PacAirEauRoute
  PacGeothermieRoute: typeof PacGeothermieRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  PompeAChaleurRoute: typeof PompeAChaleurRoute
  PompeAChaleurVsChaudiereGazRoute: typeof PompeAChaleurVsChaudiereGazRoute
  PrimeCeeRoute: typeof PrimeCeeRoute
  ReequilibrageChauffageRoute: typeof ReequilibrageChauffageRoute
  RenovationAmpleurRoute: typeof RenovationAmpleurRoute
  RenovationAppartementRoute: typeof RenovationAppartementRoute
  RenovationImmeubleRoute: typeof RenovationImmeubleRoute
  RenovationMaisonIndividuelleRoute: typeof RenovationMaisonIndividuelleRoute
  SimulationRoute: typeof SimulationRoute
  VmcVentilationRoute: typeof VmcVentilationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aides-financieres-2026': {
      id: '/aides-financieres-2026'
      path: '/aides-financieres-2026'
      fullPath: '/aides-financieres-2026'
      preLoaderRoute: typeof AidesFinancieres2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-energetique': {
      id: '/audit-energetique'
      path: '/audit-energetique'
      fullPath: '/audit-energetique'
      preLoaderRoute: typeof AuditEnergetiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eco-ptz': {
      id: '/eco-ptz'
      path: '/eco-ptz'
      fullPath: '/eco-ptz'
      preLoaderRoute: typeof EcoPtzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isolation-combles': {
      id: '/isolation-combles'
      path: '/isolation-combles'
      fullPath: '/isolation-combles'
      preLoaderRoute: typeof IsolationComblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isolation-murs': {
      id: '/isolation-murs'
      path: '/isolation-murs'
      fullPath: '/isolation-murs'
      preLoaderRoute: typeof IsolationMursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isolation-planchers': {
      id: '/isolation-planchers'
      path: '/isolation-planchers'
      fullPath: '/isolation-planchers'
      preLoaderRoute: typeof IsolationPlanchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isolation-thermique': {
      id: '/isolation-thermique'
      path: '/isolation-thermique'
      fullPath: '/isolation-thermique'
      preLoaderRoute: typeof IsolationThermiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maprimerenov': {
      id: '/maprimerenov'
      path: '/maprimerenov'
      fullPath: '/maprimerenov'
      preLoaderRoute: typeof MaprimerenovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menuiseries-fenetres': {
      id: '/menuiseries-fenetres'
      path: '/menuiseries-fenetres'
      fullPath: '/menuiseries-fenetres'
      preLoaderRoute: typeof MenuiseriesFenetresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nos-zones-d-intervention': {
      id: '/nos-zones-d-intervention'
      path: '/nos-zones-d-intervention'
      fullPath: '/nos-zones-d-intervention'
      preLoaderRoute: typeof NosZonesDInterventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-methode': {
      id: '/notre-methode'
      path: '/notre-methode'
      fullPath: '/notre-methode'
      preLoaderRoute: typeof NotreMethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pac-air-air': {
      id: '/pac-air-air'
      path: '/pac-air-air'
      fullPath: '/pac-air-air'
      preLoaderRoute: typeof PacAirAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pac-air-eau': {
      id: '/pac-air-eau'
      path: '/pac-air-eau'
      fullPath: '/pac-air-eau'
      preLoaderRoute: typeof PacAirEauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pac-geothermie': {
      id: '/pac-geothermie'
      path: '/pac-geothermie'
      fullPath: '/pac-geothermie'
      preLoaderRoute: typeof PacGeothermieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pompe-a-chaleur': {
      id: '/pompe-a-chaleur'
      path: '/pompe-a-chaleur'
      fullPath: '/pompe-a-chaleur'
      preLoaderRoute: typeof PompeAChaleurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pompe-a-chaleur-vs-chaudiere-gaz': {
      id: '/pompe-a-chaleur-vs-chaudiere-gaz'
      path: '/pompe-a-chaleur-vs-chaudiere-gaz'
      fullPath: '/pompe-a-chaleur-vs-chaudiere-gaz'
      preLoaderRoute: typeof PompeAChaleurVsChaudiereGazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime-cee': {
      id: '/prime-cee'
      path: '/prime-cee'
      fullPath: '/prime-cee'
      preLoaderRoute: typeof PrimeCeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reequilibrage-chauffage': {
      id: '/reequilibrage-chauffage'
      path: '/reequilibrage-chauffage'
      fullPath: '/reequilibrage-chauffage'
      preLoaderRoute: typeof ReequilibrageChauffageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovation-ampleur': {
      id: '/renovation-ampleur'
      path: '/renovation-ampleur'
      fullPath: '/renovation-ampleur'
      preLoaderRoute: typeof RenovationAmpleurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovation-appartement': {
      id: '/renovation-appartement'
      path: '/renovation-appartement'
      fullPath: '/renovation-appartement'
      preLoaderRoute: typeof RenovationAppartementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovation-immeuble': {
      id: '/renovation-immeuble'
      path: '/renovation-immeuble'
      fullPath: '/renovation-immeuble'
      preLoaderRoute: typeof RenovationImmeubleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovation-maison-individuelle': {
      id: '/renovation-maison-individuelle'
      path: '/renovation-maison-individuelle'
      fullPath: '/renovation-maison-individuelle'
      preLoaderRoute: typeof RenovationMaisonIndividuelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vmc-ventilation': {
      id: '/vmc-ventilation'
      path: '/vmc-ventilation'
      fullPath: '/vmc-ventilation'
      preLoaderRoute: typeof VmcVentilationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AidesFinancieres2026Route: AidesFinancieres2026Route,
  AuditEnergetiqueRoute: AuditEnergetiqueRoute,
  ContactRoute: ContactRoute,
  EcoPtzRoute: EcoPtzRoute,
  IsolationComblesRoute: IsolationComblesRoute,
  IsolationMursRoute: IsolationMursRoute,
  IsolationPlanchersRoute: IsolationPlanchersRoute,
  IsolationThermiqueRoute: IsolationThermiqueRoute,
  MaprimerenovRoute: MaprimerenovRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MenuiseriesFenetresRoute: MenuiseriesFenetresRoute,
  NosZonesDInterventionRoute: NosZonesDInterventionRoute,
  NotreMethodeRoute: NotreMethodeRoute,
  PacAirAirRoute: PacAirAirRoute,
  PacAirEauRoute: PacAirEauRoute,
  PacGeothermieRoute: PacGeothermieRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  PompeAChaleurRoute: PompeAChaleurRoute,
  PompeAChaleurVsChaudiereGazRoute: PompeAChaleurVsChaudiereGazRoute,
  PrimeCeeRoute: PrimeCeeRoute,
  ReequilibrageChauffageRoute: ReequilibrageChauffageRoute,
  RenovationAmpleurRoute: RenovationAmpleurRoute,
  RenovationAppartementRoute: RenovationAppartementRoute,
  RenovationImmeubleRoute: RenovationImmeubleRoute,
  RenovationMaisonIndividuelleRoute: RenovationMaisonIndividuelleRoute,
  SimulationRoute: SimulationRoute,
  VmcVentilationRoute: VmcVentilationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
