export const products = [
  {
    id: 201,
    name: "Apex Pro",
    price: 89.90,
    originalPrice: 149.90,
    category: "Récupération musculaire",
    badge: "Bestseller",
    description: "Pistolet de massage percussif haute performance. 6 niveaux de percussion (1 800–3 200 RPM), moteur brushless silencieux < 45 dB, autonomie 6h via USB-C. 5 têtes interchangeables incluses.",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=900&q=85",
    supplier: "https://cjdropshipping.com/",
    supplierPrice: 28.00,
    rating: 4.9,
    reviews: 1284,
    seoTitle: "Pistolet de Massage Percussif Apex Pro | SŌMA",
    seoDescription: "Pistolet de massage Apex Pro — 6 niveaux, moteur silencieux < 45 dB, 6h d'autonomie USB-C, 5 têtes incluses. Récupérez plus vite. Livraison offerte.",
    keywords: "pistolet de massage, massage gun, massage percussif, récupération musculaire, appareil de massage sport",
    features: ["6 niveaux — 1 800 à 3 200 RPM", "Moteur brushless silencieux < 45 dB", "Autonomie 6h · Charge USB-C", "5 têtes de massage incluses", "Certifié CE · Poids 1,1 kg"],
  },
  {
    id: 202,
    name: "EMS Lift",
    price: 64.90,
    originalPrice: 109.90,
    category: "Beauté & Visage",
    badge: "Premium",
    description: "Appareil facial EMS & microcourant pour un lifting non-invasif. Tonifie les muscles du visage, réduit les rides et améliore l'éclat de la peau en 4 semaines d'utilisation régulière.",
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=900&q=85",
    supplier: "https://cjdropshipping.com/",
    supplierPrice: 18.00,
    rating: 4.8,
    reviews: 647,
    seoTitle: "Appareil Lifting Facial EMS Lift | SŌMA",
    seoDescription: "Lifting facial EMS non-invasif. Tonifie les muscles, réduit les rides, améliore l'éclat en 4 semaines. Livraison offerte dès 60€.",
    keywords: "appareil EMS visage, lifting facial, microcourant visage, tonifier visage, anti-rides électronique",
    features: ["Technologie EMS + microcourant", "5 modes d'intensité réglables", "Résultats visibles en 4 semaines", "Rechargeable USB-C · LED indicator", "Compatible toutes peaux"],
  },
  {
    id: 203,
    name: "Cervix Heat",
    price: 74.90,
    originalPrice: 129.90,
    category: "Nuque & Épaules",
    badge: "Indispensable",
    description: "Masseur cervical infrarouge avec chaleur thérapeutique. Nœuds de massage shiatsu + chaleur infrarouge jusqu'à 45°C pour soulager les tensions de la nuque, épaules et cou après une longue journée.",
    image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=900&q=85",
    supplier: "https://cjdropshipping.com/",
    supplierPrice: 22.00,
    rating: 4.9,
    reviews: 892,
    seoTitle: "Masseur Cervical Infrarouge Cervix Heat | SŌMA",
    seoDescription: "Masseur cervical shiatsu + chaleur infrarouge 45°C. Soulage nuque, épaules et cou. Résultat immédiat. Livraison offerte dès 60€.",
    keywords: "masseur cervical, massage nuque, masseur épaules, chaleur infrarouge, masseur shiatsu cervical",
    features: ["Chaleur infrarouge réglable jusqu'à 45°C", "Massage shiatsu 3D bidirectionnel", "3 vitesses + 3 niveaux de chaleur", "Batterie 2 500 mAh · Charge USB-C", "Housse de protection incluse"],
  },
  {
    id: 204,
    name: "Oculus Zen",
    price: 49.90,
    originalPrice: 79.90,
    category: "Relaxation",
    badge: null,
    description: "Masque de massage oculaire à compression d'air et chaleur douce. Soulage la fatigue oculaire, les maux de tête et améliore la qualité du sommeil. Idéal pour les travailleurs sur écran.",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=85",
    supplier: "https://cjdropshipping.com/",
    supplierPrice: 14.00,
    rating: 4.7,
    reviews: 423,
    seoTitle: "Masque Massage Oculaire Oculus Zen | SŌMA",
    seoDescription: "Masque massage yeux — compression d'air + chaleur douce. Soulage fatigue oculaire et maux de tête. Améliore le sommeil. Livraison offerte.",
    keywords: "masque massage yeux, massage oculaire, fatigue oculaire, masque relaxant yeux, masque sommeil",
    features: ["Compression d'air multi-zones", "Chaleur douce 40–42°C", "Musique intégrée · Bluetooth 5.0", "5 modes de massage", "Pliable · Idéal voyage"],
  },
  {
    id: 205,
    name: "Lumbar Plus",
    price: 84.90,
    originalPrice: 139.90,
    category: "Dos & Lombaires",
    badge: null,
    description: "Coussin massant lombaire avec 9 nœuds de massage shiatsu et chaleur infrarouge. Conçu pour les voitures, bureaux et canapés. Soulage les douleurs dorsales chroniques en quelques minutes.",
    image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=900&q=85",
    supplier: "https://cjdropshipping.com/",
    supplierPrice: 26.00,
    rating: 4.8,
    reviews: 561,
    seoTitle: "Coussin Massant Lombaire Lumbar Plus | SŌMA",
    seoDescription: "Coussin massage lombaire — 9 nœuds shiatsu + chaleur infrarouge. Pour voiture, bureau et canapé. Soulage le dos. Livraison offerte dès 60€.",
    keywords: "coussin massant dos, massage lombaire, coussin massage voiture, massage dos bureau, shiatsu dos",
    features: ["9 nœuds shiatsu 3D bidirectionnels", "Chaleur infrarouge thérapeutique", "Intensité et chaleur réglables", "Compatible voiture + prise allume-cigare", "Housse lavable en machine"],
  },
  {
    id: 206,
    name: "Solea Pro",
    price: 59.90,
    originalPrice: 99.90,
    category: "Pieds & Jambes",
    badge: null,
    description: "Bain de pieds massant à bulles et vibrations. Rouleaux de massage plantaire intégrés, bulles de relaxation, chaleur réglable et LED bleue pour une expérience spa à la maison.",
    image: "https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=900&q=85",
    supplier: "https://cjdropshipping.com/",
    supplierPrice: 18.00,
    rating: 4.6,
    reviews: 318,
    seoTitle: "Bain de Pieds Massant Solea Pro | SŌMA",
    seoDescription: "Bain de pieds massant — bulles, vibrations, rouleaux plantaires, chaleur réglable. Spa à la maison. Livraison offerte dès 60€.",
    keywords: "bain de pieds massant, bain pieds électrique, spa pieds, masseur plantaire, bain pieds bulles",
    features: ["Bulles d'air + vibrations plantaires", "Chaleur réglable jusqu'à 48°C", "Rouleaux de massage intégrés", "LED thérapeutique bleue", "Cuve antidérapante XL"],
  },
]
