/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbonnementsRouteImport } from './routes/abonnements'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as FacturesRouteImport } from './routes/factures'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as SituationsRouteImport } from './routes/situations'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TresorerieRouteImport } from './routes/tresorerie'
import { Route as PortailIdRouteImport } from './routes/portail.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementsRoute = AbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturesRoute = FacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationsRoute = SituationsRouteImport.update({
  id: '/situations',
  path: '/situations',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TresorerieRoute = TresorerieRouteImport.update({
  id: '/tresorerie',
  path: '/tresorerie',
  getParentRoute: () => rootRouteImport,
} as any)
const PortailIdRoute = PortailIdRouteImport.update({
  id: '/portail/$id',
  path: '/portail/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/catalogue': typeof CatalogueRoute
  '/clients': typeof ClientsRoute
  '/connexion': typeof ConnexionRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/factures': typeof FacturesRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/situations': typeof SituationsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/tarifs': typeof TarifsRoute
  '/tresorerie': typeof TresorerieRoute
  '/portail/$id': typeof PortailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/catalogue': typeof CatalogueRoute
  '/clients': typeof ClientsRoute
  '/connexion': typeof ConnexionRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/factures': typeof FacturesRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/situations': typeof SituationsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/tarifs': typeof TarifsRoute
  '/tresorerie': typeof TresorerieRoute
  '/portail/$id': typeof PortailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnements': typeof AbonnementsRoute
  '/catalogue': typeof CatalogueRoute
  '/clients': typeof ClientsRoute
  '/connexion': typeof ConnexionRoute
  '/depenses': typeof DepensesRoute
  '/devis': typeof DevisRoute
  '/factures': typeof FacturesRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/paiements': typeof PaiementsRoute
  '/parametres': typeof ParametresRoute
  '/pipeline': typeof PipelineRoute
  '/situations': typeof SituationsRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
  '/tarifs': typeof TarifsRoute
  '/tresorerie': typeof TresorerieRoute
  '/portail/$id': typeof PortailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnements'
    | '/catalogue'
    | '/clients'
    | '/connexion'
    | '/depenses'
    | '/devis'
    | '/factures'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/parametres'
    | '/pipeline'
    | '/situations'
    | '/tableau-de-bord'
    | '/tarifs'
    | '/tresorerie'
    | '/portail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnements'
    | '/catalogue'
    | '/clients'
    | '/connexion'
    | '/depenses'
    | '/devis'
    | '/factures'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/parametres'
    | '/pipeline'
    | '/situations'
    | '/tableau-de-bord'
    | '/tarifs'
    | '/tresorerie'
    | '/portail/$id'
  id:
    | '__root__'
    | '/'
    | '/abonnements'
    | '/catalogue'
    | '/clients'
    | '/connexion'
    | '/depenses'
    | '/devis'
    | '/factures'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/paiements'
    | '/parametres'
    | '/pipeline'
    | '/situations'
    | '/tableau-de-bord'
    | '/tarifs'
    | '/tresorerie'
    | '/portail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementsRoute: typeof AbonnementsRoute
  CatalogueRoute: typeof CatalogueRoute
  ClientsRoute: typeof ClientsRoute
  ConnexionRoute: typeof ConnexionRoute
  DepensesRoute: typeof DepensesRoute
  DevisRoute: typeof DevisRoute
  FacturesRoute: typeof FacturesRoute
  InscriptionRoute: typeof InscriptionRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  PaiementsRoute: typeof PaiementsRoute
  ParametresRoute: typeof ParametresRoute
  PipelineRoute: typeof PipelineRoute
  SituationsRoute: typeof SituationsRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
  TarifsRoute: typeof TarifsRoute
  TresorerieRoute: typeof TresorerieRoute
  PortailIdRoute: typeof PortailIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnements': {
      id: '/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AbonnementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factures': {
      id: '/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof FacturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situations': {
      id: '/situations'
      path: '/situations'
      fullPath: '/situations'
      preLoaderRoute: typeof SituationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tresorerie': {
      id: '/tresorerie'
      path: '/tresorerie'
      fullPath: '/tresorerie'
      preLoaderRoute: typeof TresorerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portail/$id': {
      id: '/portail/$id'
      path: '/portail/$id'
      fullPath: '/portail/$id'
      preLoaderRoute: typeof PortailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementsRoute: AbonnementsRoute,
  CatalogueRoute: CatalogueRoute,
  ClientsRoute: ClientsRoute,
  ConnexionRoute: ConnexionRoute,
  DepensesRoute: DepensesRoute,
  DevisRoute: DevisRoute,
  FacturesRoute: FacturesRoute,
  InscriptionRoute: InscriptionRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  PaiementsRoute: PaiementsRoute,
  ParametresRoute: ParametresRoute,
  PipelineRoute: PipelineRoute,
  SituationsRoute: SituationsRoute,
  TableauDeBordRoute: TableauDeBordRoute,
  TarifsRoute: TarifsRoute,
  TresorerieRoute: TresorerieRoute,
  PortailIdRoute: PortailIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
